Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@bhushanchauhan477 
bhushanchauhan477
/
new-jenkins-pipeline-repo
1
00
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
new-jenkins-pipeline-repo/my-maven-app-eclipse/Jenkinsfile
@bhushanchauhan477
bhushanchauhan477 Update Jenkinsfile
Latest commit 908191a 14 hours ago
 History
 1 contributor
40 lines (35 sloc)  782 Bytes
  
pipeline {
  agent any
  stages {	
	stage('Maven Compile'){
		steps{
			echo 'Project compile stage'
			bat label: 'Compilation running', script: '''mvn compile'''
	       	}
	}
	
	stage('Unit Test') {
	   steps {
			echo 'Project Testing stage'
			bat label: 'Test running', script: '''mvn test'''
	       
       }
   	}	
        
    stage('Jacoco Coverage Report') {
        steps{
            jacoco()
		}
	}
        
	stage('SonarQube'){
         steps{
            bat label: '', script: '''mvn sonar:sonar \
		 -Dsonar.host.url=http://localhost:9000 \
 		-Dsonar.login=85f6125285e9864f05cd215671af1c3624c33f44'''
          }
	}

	stage('Maven Package'){
		steps{
			echo 'Project packaging stage'
			bat label: 'Project packaging', script: '''mvn package'''
		}
	} 
    }
}
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
